name = "go2go"
main = "src/index.js"
compatibility_date = "2023-10-25"

routes = [
	{ pattern = "go.avoine.fun/*", zone_name = "avoine.fun" }
]

#workers_dev = false

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
[[durable_objects.bindings]]
name = "games"
class_name = "GoGame"

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/learning/using-durable-objects#configure-durable-object-classes-with-migrations
[[migrations]]
tag = "v1"
new_classes = ["GoGame"]
